export const preset_list = [
    "A contemporary design chair, white, metal legs",
    "A iron axe, fantasy game axe, medieval",
    "A blue vintage car, cartoon, white stripes",
    "A wooden boat, 13th century, medieval",
    "A single 3D low poly orange cat, smiling, cartoon",
    "A green dragon, fantasy, medieval, wings",
    "A grey dolphin playing with a ball, cartoon",
    "A futuristic silver laptop, sleek design",
    "A steampunk wristwatch, bronze gears, leather strap",
    "A glass teapot, minimalist design, wooden handle",
    "A red robotic vacuum cleaner, futuristic, shiny",
    "A rustic wooden lantern, candle inside, vintage",
    "A floating magic wand, glowing, fantasy",
    "A golden treasure chest, pirate style, jewels",
    "A cyberpunk helmet, neon lights, black matte finish",
    "A cute plush teddy bear, brown, bow tie",
    "A crystal ball, mystical, swirling colors inside",
    "A sleek black racing bike, aerodynamic, modern",
    "A magical spellbook, ancient, glowing runes",
    "A bamboo flute, traditional, engraved patterns",
    "A robotic arm, silver, detailed joints",
    "A vintage typewriter, black, with paper",
    "A ceramic coffee mug, blue, with a funny quote",
    "A leather-bound journal, old, with a quill pen",
    "A neon green basketball, glowing, rainbow",
    "A silver spaceship, sleek design, with thrusters",
    "A miniature bonsai tree, detailed, in a ceramic pot",
    "A VR headset, black, with blue accents",
    "A pair of roller skates, retro design, bright colors",
    "A golden pocket watch, intricate details, chain",
    "A vintage camera, black and silver, with a strap",
    "A red electric guitar, glossy finish, rock style",
    "A futuristic drone, black, with blue lights",
    "A traditional samurai sword, detailed hilt, blade",
    "A traditional samurai helmet, red and black, horns",
    "A colorful hot air balloon, floating in the sky",
    "A sleek white yacht, modern design, on the water",
    "A rustic birdhouse, wooden, with a thatched roof",
    "A sci-fi blaster gun, black and red, glowing parts",
    "A marble chess set, black and white, with pieces",
    "A golden crown, detailed, with gemstones",
    "A futuristic jetpack, silver, with thrusters",
    "A magical potion bottle, glowing liquid, cork",
    "A vintage gramophone, brass horn, wooden base",
    "A pair of binoculars, black, with adjustable focus",
    "A golden compass, detailed, with cardinal points",
    "A wooden cuckoo clock, carved details, pendulum",
    "A futuristic ray gun, silver, glowing barrel",
    "A pair of brass candlesticks, ornate design",
    "A wooden rocking horse, traditional, with mane",
    "A silver pocket watch, intricate details, chain",
    "A wooden treasure chest, pirate style, gold coins",
    "A computer keyboard, black, with glowing keys",
    "A designer handbag, leather, with gold accents",
    "A pair of sunglasses, aviator style, mirrored",
    "A vintage microphone, silver, with stand",
    "A design lamp, modern, with adjustable arm",
    "A design sofa, modern, with cushions",
    "A golden trophy cup, detailed, with base",
    "A gecko lizard, green, detailed scales",
    "A wooden barrel, rustic, with metal bands",
    "A whale shark, underwater, detailed fins",
    "A race car, red, with white stripes",
    "A vintage bicycle, black, with basket",
    "A salmon fish, underwater, detailed scales",
    "A table lamp, modern, with fabric shade",
    "A wooden chair, traditional, with cushion",
    "A wooden table, rustic, with carved legs",
    "A wooden bench, outdoor, with backrest",
    "A wooden wardrobe, vintage, with drawers",
    "A wooden bed, traditional, with headboard",
    "A wooden desk, antique, with drawers",
    "A music box, vintage, with dancing ballerina",
    "A silver teapot, traditional, with handle",
    "A silver spoon, ornate, with engraved pattern",
    "A crystal vase, elegant, with floral design",
    "A iron horseshoe, rustic, with nails",
    "A copper kettle, vintage, with wooden handle",
    "A chocolate cake, delicious, with icing",
    "A strawberry ice cream, refreshing, in a cone",
    "A banana smoothie, healthy, with straw",
    "A pepperoni pizza, tasty, with cheese",
    "A sushi roll, delicious, with wasabi",
    "A cup of coffee, aromatic, with steam",
    "A glass of wine, red, with grapes",
    "A bottle of champagne, sparkling, with cork",
    "A birthday cake, colorful, with candles",
    "A chocolate bar, sweet, with nuts",
    "A bowl of fruit salad, fresh, with kiwi",
    "A plate of spaghetti, delicious, with sauce",
    "A cheeseburger, juicy, with fries",
    "A hot dog, grilled, with mustard",
    "A taco, spicy, with salsa",
    "A plate of sushi, fresh, with soy sauce",
    "A blue cow, cartoon, with dots",
    "A green frog, cartoon, with big eyes",
    "A pink pig, cartoon, with curly tail",
    "A yellow duck, cartoon, with orange beak",
    "A brown horse, cartoon, with saddle",
    "A creepy doll, old, with cracked paint",
    "A scary clown, circus, with red nose",
    "A spooky ghost, floating, with chains",
    "A black cat, Halloween, with glowing eyes",
    "A witch hat, pointed, with buckle",
    "An abandoned truck, rusty, with flat tires",
];
